export const data = [
    {
        name:'Ramesh',
        age:10,
        address:'Lucknow',
        children:5
    },
    {
        name:'Mahesh',
        age:20,
        address:'Kanpur',
        children:4
    },
    {
        name:'Nilesh',
        age:30,
        address:'Bareilly',
        children:12
    },
    {
        name:'Ramesh',
        age:40,
        address:'Meerut',
        children:2
    },
    {
        name:'Rohit',
        age:50,
        address:'Delhi',
        children:1
    },
    {
        name:'Shivam',
        age:60,
        address:'Noida',
        children:0
    },
    {
        name:'Vaibhav',
        age:70,
        address:'Punjab',
        children:15
    },
    {
        name:'Karan',
        age:80,
        address:'Rohtak',
        children:33
    },
    {
        name:'Rohit',
        age:90,
        address:'Rampur',
        children:2
    },
    {
        name:'Rahul',
        age:100,
        address:'Bihar',
        children:10
    },
    {
        name:'Ramesh',
        age:10,
        address:'Lucknow',
        children:5
    },
    {
        name:'Mahesh',
        age:20,
        address:'Kanpur',
        children:4
    },
    {
        name:'Nilesh',
        age:30,
        address:'Bareilly',
        children:12
    },
    {
        name:'Ramesh',
        age:40,
        address:'Meerut',
        children:2
    },
    {
        name:'Rohit',
        age:50,
        address:'Delhi',
        children:1
    },
    {
        name:'Shivam',
        age:60,
        address:'Noida',
        children:0
    },
    {
        name:'Vaibhav',
        age:70,
        address:'Punjab',
        children:15
    },
    {
        name:'Karan',
        age:80,
        address:'Rohtak',
        children:33
    },
    {
        name:'Rohit',
        age:90,
        address:'Rampur',
        children:2
    },
    {
        name:'Rahul',
        age:100,
        address:'Bihar',
        children:10
    }
]